# Регистрация пользователя
POST http://localhost:5000/api/v1/auth/sign-up
Content-Type: application/json

{"username":  "user", "password":  "11111111"}

###

# вход пользователя
POST http://localhost:5000/api/v1/auth/sign-in
Content-Type: application/json

{"username":  "user", "password":  "11111111"}

###

# добавление роли пользователю
POST http://localhost:5000/api/v1/roles/assign
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjM1MzE5OTUxLCJqdGkiOiI2YTQxNzQ4My04OGYxLTQ1NWQtOTFkYy0xNGRmNzY3MmE4YjYiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoiZWI0NzBjOTItY2I2OS00NjUxLWFkOGQtOWRhNjQ2NmIwOTg5IiwibmJmIjoxNjM1MzE5OTUxLCJleHAiOjE2MzUzMjA4NTEsInJ0IjoiZjEyMzhiODMtYjIzZS00MDM1LTk0MjQtYTM3Njg1OTdlMjg4IiwidXIiOlsiQWRtaW4iXX0.jHzfBt6TD_4GsmGPL5gtv4jF5bpUM-noNmL3qy_-f4c

{"user_id":  "4c14a10c-21d4-4878-a6a9-9f1bd6735f53", "role_name":  "bargur"}

###

# создание роли
POST http://localhost:5000/api/v1/roles
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjM1MzE5OTUxLCJqdGkiOiI2YTQxNzQ4My04OGYxLTQ1NWQtOTFkYy0xNGRmNzY3MmE4YjYiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoiZWI0NzBjOTItY2I2OS00NjUxLWFkOGQtOWRhNjQ2NmIwOTg5IiwibmJmIjoxNjM1MzE5OTUxLCJleHAiOjE2MzUzMjA4NTEsInJ0IjoiZjEyMzhiODMtYjIzZS00MDM1LTk0MjQtYTM3Njg1OTdlMjg4IiwidXIiOlsiQWRtaW4iXX0.jHzfBt6TD_4GsmGPL5gtv4jF5bpUM-noNmL3qy_-f4c

{"name":  "bargur"}
