POST http://localhost:5000/auth/sign-up
Content-Type: application/json

{"username":  "loshara2kkk", "password": "123455555555", "email":  "lol@cokm.ru"}

###
GET http://localhost:5000/ping
Accept: application/json

###
